backend:
  name: github
  repo: wijohnst/theroycecolumbus.com_v_2.0

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: src/blog
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: 'pages'
    label: "Pages"
    files:
      - label: 'Menu'
        name: "menu"
        file: "src/content/menu.json"
        widget: "object"
        fields:
          - label: Appetizers
            name : appetizers_list
            widget: list
            fields:
              - { label: Item Name, name: app_name, widget: string }
              - { label: Description, name: app_description, widget: text}
              - { label: Price, name: app_price, widget: string}
              - label: Allergies 
                name: app_allergies
                widget: select
                multiple: true
                options: [None, Dairy, Red Meat, Allums, Soy, Gluten, Animal Product, Fish]
                default: [None]
