backend:
  name: github
  repo: wijohnst/theroycecolumbus.com_v_2.0

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: src/blog
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: 'pages'
    label: "Pages"
    files:
      - label: 'Menu'
        name: "menu"
        file: "src/content/menu.yml"
        fields:
          - {label: Categories,  name: categories, widget: string}
